### ISSUE TITLE
Installation issue in octobercms v3 (v 3.1.11)

### ISSUE THREAD

**Issue by Anjaan2077** [blakej115/magic-forms#5]
Hi,
When i tried to install this plugin Database issue..
please solve this issue.

Thank You.
![Capture](https://user-images.githubusercontent.com/64153858/196707668-170bbf4a-441a-4a9b-b0f8-cf8a9d2f5263.PNG)

**Comment by kombimedia** [comment]
Hi there,

I'm facing the same issue..

Cheers,

Cy

**Comment by blakej115** [comment]
Hi @Anjaan2077 and @kombimedia,

Thanks for the reports!

This issue has been fixed in Magic Forms v1.6.3, just released.

You may install the plugin fresh with no issues if you've already removed it.

If you still have the plugin installed, either of the following commands should resolve the issue:

**Update everything:**

`php artisan october:update`

OR

**Refresh the plugin:**

`php artisan plugin:refresh BlakeJones.MagicForms`

Thank you!

**Comment by kombimedia** [comment]
Awesome! Sorted for me. Cheers.
